name: ${APP_NAME:-my-gova-app}

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - ./src:/src
      - ./data:/data
      - ./logs:/logs
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    env_file: .env

volumes:
  go-mod-cache:
  go-build-cache:
